# Generated by Django 5.0.4 on 2024-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsuser',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
    ]
