# Generated by Django 5.0.4 on 2024-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_bsuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
