# Generated by Django 5.0.4 on 2024-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_bsuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
