# Generated by Django 5.0.4 on 2024-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_bsuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsuser',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
